# -*- coding: utf-8 -*-
"""9강영상.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PIAamWy1CGOwltaPebZBeAHmFbkMDypr

# 9강 · 영상 생성 자동화
### 그림을 먼저 만들고, 그 그림을 움직입니다

**AI 콘텐츠 마케팅 자동화의 정석** · AI CITY BUILDERS

---

## 오늘 무엇을 하나

8강까지 우리는 **손으로** 했습니다. 나노바나나에서 그림을 만들고, 구글 Flow에 하나씩 올리고, 프롬프트를 붙여넣고, 기다렸다가 내려받았습니다. 장면이 10개면 그 과정을 10번 반복해야 했습니다.

오늘은 그 전부를 **한 번에** 시킵니다. 기획서를 적어 넣고 재생 버튼을 누르면, 장면마다 그림이 만들어지고 그 그림이 영상이 되어 파일로 저장됩니다.

### 왜 그림을 먼저 만드나

영상 AI에게 글만 주면 매번 다른 세상을 그립니다. 같은 사람이 장면마다 얼굴이 바뀌고 색감이 튑니다. 이어 붙이면 남의 영상 여러 개를 붙여 놓은 것처럼 됩니다.

그래서 순서를 바꿉니다. **먼저 그림으로 인물·장소·분위기를 확정하고, 그 그림을 첫 장면으로 주면서 움직이라고 시킵니다.** 8강에서 첫 프레임 이미지를 배운 이유가 이것이고, 오늘 그 이미지가 재료가 됩니다.

```
기획서(8강) → 그림(나노바나나 프로) → 영상(Omni 1.1) → 캡컷(10강)
```

### 오늘 쓰는 도구 둘

| | 하는 일 | 모델 |
|---|---|---|
| **나노바나나 프로** | 장면의 첫 그림을 그린다 | `nano-banana-pro-preview` |
| **Omni 1.1 Flash** | 그 그림을 10초 영상으로 움직인다 | `gemini-omni-1.1-flash` |

둘 다 같은 API 키 하나로 씁니다.

---
## ⚠️ 시작하기 전에 — 이 강의는 돈이 듭니다

지금까지 우리 과정은 0원이었습니다. **영상 생성만 예외입니다.**

- 영상 생성에는 **무료 사용량이 없습니다.** 결제 수단이 등록된 API 키가 필요합니다.
- 예전 강의에 나오는 「가입 시 300달러 무료 크레딧」은 **지금은 없습니다.**
- 공식 가격: **720p 영상 1초에 약 $0.10**. 360p는 그 **3분의 1**.
- Omni는 한 번에 **10초**를 만듭니다.

| 만드는 것 | 360p 초안 | 720p 최종 |
|---|---|---|
| 10초 장면 1개 | 약 470원 | 약 1,400원 |
| 3장면 (30초) | 약 1,400원 | 약 4,200원 |
| 10장면 (100초) | 약 4,700원 | 약 14,000원 |

### 돈을 쓰는 방식

지금 단계에서 **전부를 자동화할 필요는 없습니다.** 콘텐츠를 직접 만들어 보면서, 나중에 자동화할 부분에만 조금씩 투자하는 편이 좋습니다.

그래서 우리는 **영상 생성만** 돈을 씁니다. 분석·기획·나레이션은 로컬 AI로 0원이고, 영상도 가장 저렴한 Omni로, 그것도 **360p 초안으로 먼저 전부 만들고 마음에 드는 장면만 720p로 다시** 뽑습니다. 10장면 기준 1만 4천 원이 4천 7백 원이 됩니다.

**처음이시면 장면 1개만** 먼저 돌려 보세요. 500원이면 전체 흐름을 확인할 수 있습니다.

---
# 1단계 · 도구 설치

파이썬에게 "구글 AI를 쓸 줄 아는 능력"을 설치하는 과정입니다. 한 줄이면 됩니다.

### 여기서 꼭 알아야 할 것

Omni 1.1은 **google-genai 2.0.0 이상**에서만 작동합니다. 예전 강의나 인터넷 예제를 따라 하다 아래 오류를 만나면 십중팔구 버전 문제입니다.

> `The legacy Interactions API schema is no longer supported. Please upgrade your google-genai Python SDK to version >= 2.0.0`

아래 셀은 설치 후 버전을 **자동으로 검사**합니다. 통과하지 못하면 메뉴의 **런타임 → 세션 다시 시작**을 누르고 이 셀을 한 번 더 실행하세요.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U "google-genai>=2.0.0"

import google.genai as _g
print("설치된 버전:", _g.__version__)
assert int(_g.__version__.split(".")[0]) >= 2, \
    "2.0.0 이상이 필요합니다. 런타임 → 세션 다시 시작 후 이 셀을 다시 실행하세요."
print("✓ 준비 완료")

"""---
# 2단계 · API 키 연결

### API 키가 무엇인가

구글의 인공지능을 내 코드에서 불러다 쓰기 위한 **출입증**입니다. 이 키로 누가 얼마나 썼는지 계산되므로, **남에게 보여주면 안 됩니다.** 영상에 화면을 띄울 때도 가려야 합니다.

### 받는 곳

1. **aistudio.google.com** 접속 → 로그인
2. 오른쪽 위 **Get API key** → **Create API key**
3. 클라우드 프로젝트를 만들라고 하면 아무 이름으로 만듭니다
4. 생성된 키를 복사

> 영상 생성은 유료이므로 **결제 수단(카드) 등록**이 되어 있어야 합니다. 구글 클라우드 콘솔의 **결제(Billing)** 메뉴에서 등록합니다.

### 넣는 방법 두 가지

- **간단한 방법** — 아래 칸에 키를 붙여넣습니다. (노트북을 남과 공유하면 키도 같이 갑니다. 주의)
- **안전한 방법** — 왼쪽 **열쇠 아이콘(보안 비밀)** 에 이름을 `GEMINI_API_KEY` 로 저장하고, 노트북 접근을 켭니다. 그러면 아래 칸을 비워 둬도 자동으로 불러옵니다.

"""

from google import genai
from google.genai import types
import base64, os, time

GEMINI_API_KEY = ""  # @param {type:"string"}   ← 코드에 키를 직접 적지 않습니다. 비워 두면 .env → 환경변수 → Colab 보안 비밀 순으로 찾습니다.

if not GEMINI_API_KEY:
    # 1) 프로젝트 폴더의 .env 파일 (GEMINI_API_KEY=...)
    try:
        from dotenv import load_dotenv
        load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd(), ".env"))
    except Exception:
        pass
    GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

if not GEMINI_API_KEY:
    # 2) Colab 보안 비밀 (열쇠 아이콘)
    try:
        from google.colab import userdata
        GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')
    except Exception:
        pass

assert GEMINI_API_KEY, "API 키가 없습니다. 프로젝트 폴더의 .env 파일에 GEMINI_API_KEY=... 를 적거나, Colab이면 왼쪽 열쇠 아이콘에 GEMINI_API_KEY 로 저장하세요."

client = genai.Client(api_key=GEMINI_API_KEY)
print("✓ 연결됨")

"""---
# 3단계 · 무엇을 만들지 적기

8강 기획기가 만들어 준 내용을 여기에 옮겨 적습니다. 채울 칸은 셋뿐입니다.

### `STYLE` — 모든 장면에 똑같이 붙는 문장

장면이 바뀌어도 **절대 바꾸지 않는** 한 줄입니다. 이 문장이 영상 전체의 톤을 잡아 줍니다. 색감·질감·조명을 여기 넣고, 장면마다 달라지는 내용은 넣지 않습니다.

### `image_prompt` — 그 장면의 첫 그림

카메라가 **무엇을 보고 있는지**를 적습니다. 움직임이 아니라 **정지 화면**을 묘사한다고 생각하세요.

### `video_prompt` — 그 그림을 어떻게 움직일지

카메라의 움직임을 적습니다. 두 번째 장면부터는 **"이어서"** 로 시작하면 앞 장면과 자연스럽게 붙습니다.

| 이렇게 적으면 좋습니다 | 이유 |
|---|---|
| 카메라가 천천히 밀고 들어간다 | 카메라 움직임이 분명함 |
| 끊김 없는 한 컷 | 중간에 장면이 튀지 않음 |
| 효과음만, 나레이션 없음 | 목소리는 7강에서 만든 내 것으로 |

> **비율**: 유튜브 롱폼이면 `16:9`, 쇼츠·릴스면 `9:16`. 시작 전에 정하고 끝까지 바꾸지 않습니다.
> **화질**: 처음에는 `360p`로 전부 만들어 보고, 마음에 드는 장면만 `720p`로 다시 뽑습니다.

"""

PROJECT = "체르노빌 미스터리"   # @param {type:"string"}
ASPECT  = "9:16"              # @param ["9:16", "16:9"]
QUALITY = "360p"              # @param ["360p", "720p", "1080p"]

# 모든 장면에 똑같이 붙는 문장 — 장면이 바뀌어도 이건 바꾸지 않습니다
STYLE = "시네마틱 다큐멘터리, 차가운 청록 색감, 부드러운 자연광, 사실적인 질감, 글자 없음, 레드라인"

# 소리 규칙 — 나레이션은 7강에서 만든 내 목소리로 넣을 것이므로 여기서는 뺍니다
AUDIO_RULE = "효과음만, 나레이션 없음, 음악 없음"

SCENES = [
    {
        "image_prompt": "지하 30미터 콘크리트 터널 단면. 붉은 계측선과 수치 표기가 구조물 위에 겹쳐진다. 공중에 먼지가 떠 있다.",
        "video_prompt": "카메라가 터널 안쪽을 향해 천천히 밀고 들어간다. 끊김 없는 한 컷.",
    },
    {
        "image_prompt": "봉인된 녹슨 철문과 부식된 경고 표지판의 클로즈업. 붉은 계측선이 문틀의 치수를 가리킨다.",
        "video_prompt": "이어서. 카메라가 철문 표면을 따라 옆으로 미끄러진다. 끊김 없는 한 컷.",
    },
]

print(f"{PROJECT} · {len(SCENES)}장면 · {ASPECT} · {QUALITY}")

"""---
# 4단계 · 얼마 드는지 먼저 봅니다

**시작 전에 반드시 확인하는 습관을 들이세요.** 자동화는 편한 만큼 빠르게 돈이 나갑니다. 한 장면은 10초로 만들어집니다.

"""

SEC_PER_SCENE   = 10       # Omni 는 한 번에 10초를 만듭니다
USD_PER_SEC_720P = 0.10    # 공식 가격 (720p 기준)
RATIO = {"360p": 1/3, "720p": 1.0, "1080p": 1.0}
USD_KRW = 1400

usd = len(SCENES) * SEC_PER_SCENE * USD_PER_SEC_720P * RATIO[QUALITY]
print(f"장면 {len(SCENES)}개 × 10초 · {QUALITY}")
print(f"예상 비용: 약 ${usd:.2f}  (약 {usd*USD_KRW:,.0f}원)")
print()
print("괜찮으면 다음 셀로 넘어가세요. 부담되면 위 3단계에서 SCENES 를 한 개만 남기세요.")

"""---
# 5단계 · 첫 그림 만들기 (나노바나나 프로)

장면마다 첫 프레임 그림을 만듭니다. 8강에서 손으로 하던 그 작업입니다.

### 여기서 꼭 알아야 할 것 — 비율은 코드로 지정합니다

프롬프트에 "9:16으로" 라고 **글로 적어도 소용없습니다.** 아래처럼 설정으로 넘겨야 세로 그림이 나옵니다.

```python
config=types.GenerateContentConfig(
    image_config=types.ImageConfig(aspect_ratio=ASPECT)
)
```

이걸 빠뜨리면 쇼츠를 만들려는데 가로 그림이 나오고, 영상까지 가로로 만들어져 처음부터 다시 하게 됩니다.

### 그림이 마음에 안 들면

`STYLE` 은 그대로 두고 **`image_prompt` 만** 고쳐서 다시 실행하세요. 스타일 문장을 건드리면 장면끼리 톤이 어긋납니다.

"""

IMAGE_MODEL = "nano-banana-pro-preview"   # 나노바나나 프로

frames = []
for i, sc in enumerate(SCENES, 1):
    print(f'{i}번 장면 그림 만드는 중…')
    prompt = f"{STYLE}. {sc['image_prompt']}"
    res = client.models.generate_content(
        model=IMAGE_MODEL,
        contents=prompt,
        config=types.GenerateContentConfig(
            image_config=types.ImageConfig(aspect_ratio=ASPECT)
        ),
    )
    data = None
    for part in res.candidates[0].content.parts:
        if getattr(part, 'inline_data', None):
            data = part.inline_data.data
            break
    assert data, f'{i}번 장면 그림이 안 나왔습니다. image_prompt 를 조금 짧게 줄여서 다시 해보세요.'
    open(f'frame_{i:02d}.png', 'wb').write(data)
    frames.append(data)
    print(f'  완성 → frame_{i:02d}.png ({len(data)//1024}KB)')

from IPython.display import Image, display
print('\n만들어진 그림:')
for i in range(len(frames)):
    display(Image(f'frame_{i+1:02d}.png', width=260))

"""---
# 6단계 · 그림을 움직이기 (Omni 1.1 Flash)

이제 그림이 영상이 됩니다. 한 장면당 1~2분 걸립니다.

### 첫 장면과 다음 장면은 방식이 다릅니다

| | 무엇을 주는가 | 코드 |
|---|---|---|
| **첫 장면** | 그림 + 움직임 설명 | `input=[이미지, 텍스트]` |
| **다음 장면** | 앞 장면의 번호표 + 움직임 설명 | `previous_interaction_id=앞_장면.id` |

`previous_interaction_id` 는 **앞 장면을 이어받으라는 뜻**입니다. Omni 1.1은 이때 앞의 **10초를 참고**해서 만듭니다. 예전 모델은 마지막 1초만 봤기 때문에 이어 붙이면 장면이 튀었는데, 그 문제가 해결된 것이 이번 버전의 핵심입니다.

### 알아 두세요 — 이어붙인 결과는 "전체 영상"입니다

1장면을 만들면 10초짜리가 나오고, 2장면을 이어 붙이면 **20초짜리(앞 장면 포함)** 가 나옵니다. 3장면이면 30초입니다.

그래서 캡컷에 넣을 때는 **마지막 파일 하나만** 쓰면 됩니다. 파일을 전부 넣으면 같은 장면이 반복됩니다.

> 이어 붙이기는 **최대 40초**까지 됩니다. 더 긴 영상은 40초짜리 여러 개를 만들어 캡컷에서 잇습니다.

"""

VIDEO_MODEL = "gemini-omni-1.1-flash"

prev_id = None
made = []

for i, sc in enumerate(SCENES, 1):
    print(f'{i}번 장면 영상 만드는 중… (1~2분 걸립니다)')
    text = f"{sc['video_prompt']} {AUDIO_RULE}"
    fmt  = {'type': 'video', 'resolution': QUALITY, 'aspect_ratio': ASPECT}

    if prev_id is None:
        # 첫 장면 — 5단계에서 만든 그림을 시작 프레임으로 준다
        r = client.interactions.create(
            model=VIDEO_MODEL,
            input=[
                {'type': 'image',
                 'data': base64.b64encode(frames[i-1]).decode(),
                 'mime_type': 'image/png'},
                {'type': 'text', 'text': text},
            ],
            response_format=fmt,
        )
    else:
        # 다음 장면 — 앞 장면을 이어받는다 (앞의 10초를 참고한다)
        r = client.interactions.create(
            model=VIDEO_MODEL,
            previous_interaction_id=prev_id,
            input=[{'type': 'text', 'text': text}],
            response_format=fmt,
        )

    out  = r.output_video
    name = f'scene_{i:02d}.mp4'
    if getattr(out, 'data', None):
        open(name, 'wb').write(base64.b64decode(out.data))
    else:
        # 파일이 크면 주소로 오므로 준비될 때까지 기다렸다가 받는다
        fid = out.uri.split('/')[-1]
        while True:
            info = client.files.get(name=f'files/{fid}')
            if info.state.name == 'ACTIVE':
                break
            time.sleep(5)
        open(name, 'wb').write(client.files.download(file=out.uri))

    made.append(name)
    prev_id = r.id
    print(f'  완성 → {name} ({os.path.getsize(name)//1024}KB)')

print('\n전부 끝났습니다.')
print('만들어진 파일:', ', '.join(made))
print(f'편집에 쓸 파일: {made[-1]}  ← 이 하나가 전체 영상입니다')

"""---
# 7단계 · 확인하고 내려받기

마지막 파일이 전체 영상입니다. 먼저 보고, 마음에 들면 내려받으세요.

마음에 안 들면 **3단계로 돌아가 `video_prompt` 를 고치고 다시** 실행하면 됩니다. 그림이 문제면 5단계부터, 움직임이 문제면 6단계만 다시 하면 됩니다.

"""

from IPython.display import Video, display
display(Video(made[-1], embed=True, width=320))

from google.colab import files
files.download(made[-1])

"""---
# 막히는 곳

| 증상 | 원인과 해결 |
|---|---|
| `legacy Interactions API schema is no longer supported` | SDK 가 옛 버전입니다. 1단계를 다시 실행하고 **런타임 → 세션 다시 시작** 후 처음부터 |
| `API key not valid` / 인증 오류 | 키를 잘못 붙여넣었거나 앞뒤 공백이 섞였습니다. 다시 복사해 넣으세요 |
| 결제 관련 오류가 난다 | 영상 생성은 무료가 없습니다. 구글 클라우드 콘솔 → **결제**에서 카드를 등록하세요 |
| 쇼츠를 만들려는데 가로로 나온다 | 5단계의 `image_config` 비율 설정을 빠뜨린 것입니다 |
| 장면마다 인물·분위기가 다르다 | `STYLE` 을 도중에 바꿨거나, 이어붙이기(`previous_interaction_id`) 없이 따로 만든 것입니다 |
| 사람 목소리가 들어가 있다 | `AUDIO_RULE` 이 프롬프트에 붙었는지 확인하세요 |
| 그림이 안 나온다 | `image_prompt` 가 너무 깁니다. 한두 문장으로 줄이세요 |
| 돈이 얼마나 나갈지 무섭다 | 4단계에서 먼저 계산하고, 장면 1개·360p 로 연습하세요 |

> 여기 없는 문제는 **오류 메시지를 그대로 복사해서** 안티그래비티나 제미나이에 붙여 넣고 물어보세요. 그 답을 읽고 고쳐 보는 것이 이 과정에서 기르려는 능력입니다.

---
# 다음에 할 것

1. 내려받은 mp4를 **캡컷**에 넣습니다.
2. **7강에서 만든 내 목소리 나레이션**을 아래 트랙에 깔고, 파형을 보며 길이를 맞춥니다.
3. 자동 자막(한국어)을 넣고, 배경음악은 **더킹**으로 말할 때 낮춥니다.
4. 유튜브는 **16:9**, 쇼츠·릴스는 **9:16** 로 각각 내보냅니다.

10강에서 이것을 플랫폼마다 다르게 발행합니다.

---

*AI CITY BUILDERS · AI 콘텐츠 마케팅 자동화의 정석 · 9강 실습 자료*
*가격·모델 정보는 2026년 8월 공식 기준입니다.*
"""